/*
lists will contain ALL stimulus lists (the correct one is chosen automatically for each participant)
enter one list per [ ] entry in lists, as seen below, with a corresponding stimulusList parameter

stimulusList contains test trials as well as target trials. this is implented via blocks. Block0 will be handled as test trials.

column descriptors:
0: list number
1: stimulus number
2: stimulus blocks
3: audio file ('pp' or 'participant' for a recording trial)
4: image file left hand side
5: image file right hand side
*/

var lists = [
  // 0: List1 hesitant written sentences (cheap + expensive) Complete.docx
  [
    [0, 0, 1, 'A bra is uhm more expensive than a book (HES).wav', 'bra_2.png', 'book_2.png'],
    [0, 1, 1, 'participant', 'pizza_2.png', 'suitcase_2.png'],
    [0, 2, 1, 'An iron is cheaper than a telly.wav', 'iron_2.png', 'Telly_2.png'],
    [0, 3, 1, 'participant', 'violin_2.png', 'tent_2.png'],
    [0, 4, 1, 'A barbeque is more expensive than a biscuit.wav', 'barbecue_2.png', 'biscuit_2.png'],
    [0, 5, 1, 'participant', 'pear_2.png', 'lamp_2.png'],
    [0, 6, 1, 'A nail is cheaper than a uhm spoon.wav', 'nail2_2.png', 'spoon_2.png'],
    [0, 7, 1, 'participant', 'hat_2.png', 'candle_2.png'],
    [0, 8, 1, 'block 8, sentence -01.wav', 'Telly_2.png', 'apple_2.png'],
    [0, 9, 1, 'participant', 'banana_2.png', 'umbrella_2.png'],
    [0, 10, 1, 'block 8, sentence -02.wav', 'biscuit_2.png', 'ashtray_2.png'],
    [0, 11, 1, 'participant', 'balloon_2.png', 'lemon_2.png'],
    [0, 12, 1, 'block 8, sentence -03.wav', 'banana_2.png', 'Globe_2.png'],
    [0, 13, 1, 'participant', 'pillow_2.png', 'Telly_2.png'],
    [0, 14, 1, 'block 8, sentence -04.wav', 'chair_2.png', 'Lock_2.png'],
    [0, 15, 1, 'participant', 'scissors_2.png', 'biscuit_2.png'],
    [0, 16, 1, 'block 8, sentence -05.wav', 'Refrigerator_2.png', 'brush_2.png'],
    [0, 17, 1, 'participant', 'volleyball_2.png', 'button_2.png'],
    [0, 18, 1, 'A belt is cheaper than a rucksack.wav', 'belt_2.png', 'Rucksack_2.png'],
    [0, 19, 1, 'participant', 'lemon_2.png', 'bra_2.png'],
    [0, 20, 1, 'A basket is UHM more expensive than a book (HES).wav', 'basket_2.png', 'book_2.png'],
    [0, 21, 1, 'participant', 'iron_2.png', 'scarf_2.png'],
    [0, 22, 1, 'A watermelon is cheaper than a refrigerator.wav', 'watermelon_2.png', 'Refrigerator_2.png'],
    [0, 23, 1, 'participant', 'clock_2.png', 'iron_2.png'],
    [0, 24, 1, 'A rucksack is more expensive than a lemon.wav', 'Rucksack_2.png', 'lemon_2.png'],
    [0, 25, 1, 'participant', 'scarf_2.png', 'calculator_2.png'],
    [0, 26, 1, 'A razor is  UHM more expensive than a watermelon (HES).wav', 'razor_2.png', 'watermelon_2.png'],
    [0, 27, 1, 'participant', 'Refrigerator_2.png', 'bench_2.png'],
    [0, 28, 1, 'Scissors are more expensive than bread.wav', 'scissors_2.png', 'bread_2.png'],
    [0, 29, 1, 'participant', 'glasses_2.png', 'Rucksack_2.png'],
    [0, 30, 1, 'A hoover is more expensive than a tie.wav', 'hoover_2.png', 'tie_2.png'],
    [0, 31, 1, 'participant', 'sandwich_2.png', 'perfume_2.png'],
    [0, 32, 1, 'An aeroplane is more expensive than a nail.wav', 'Aeroplane_2.png', 'nail2_2.png'],
    [0, 33, 1, 'participant', 'camera_2.png', 'laptop_2.png'],
    [0, 34, 1, 'A watch is more expensive than a uhm drum (HES).wav', 'watch_2.png', 'drum_2.png'],
    [0, 35, 1, 'participant', 'apple_2.png', 'house_2.png'],
    [0, 36, 1, 'A hammer is cheaper than a hoover.wav', 'hammer_2.png', 'hoover_2.png'],
    [0, 37, 1, 'participant', 'suitcase_2.png', 'house_2.png'],
    [0, 38, 1, 'A cake a is cheaper than an aeroplane.wav', 'cake_2.png', 'Aeroplane_2.png'],
    [0, 39, 1, 'participant', 'volleyball_2.png', 'calculator_2.png'],
    [0, 40, 1, 'A mixer is more expensive than a uhm skirt (HES).wav', 'mixer_2.png', 'skirt_2.png'],
    [0, 41, 1, 'participant', 'hoover_2.png', 'bench_2.png'],
    [0, 42, 1, 'A pencil is cheaper than a uhm radio.wav', 'pencil_2.png', 'radio_2.png'],
    [0, 43, 1, 'participant', 'Aeroplane_2.png', 'spoon_2.png'],
    [0, 44, 2, 'A lock is more expensive than a rubber.wav', 'Lock_2.png', 'rubber_2.png'],
    [0, 45, 2, 'participant', 'razor_2.png', 'glasses_2.png'],
    [0, 46, 2, 'A sledge is more expensive than a whistle.wav', 'Sledge_2.png', 'whistle_2.png'],
    [0, 47, 2, 'participant', 'camera_2.png', 'basket_2.png'],
    [0, 48, 2, 'A cake is cheaper than a camera.wav', 'cake_2.png', 'camera_2.png'],
    [0, 49, 2, 'participant', 'drum_2.png', 'lipstick_2.png'],
    [0, 50, 2, 'A rubber is cheaper than a tent.wav', 'rubber_2.png', 'tent_2.png'],
    [0, 51, 2, 'participant', 'egg_2.png', 'button_2.png'],
    [0, 52, 2, 'A tie is cheaper than a sledge.wav', 'tie_2.png', 'Sledge_2.png'],
    [0, 53, 2, 'participant', 'bed_2.png', 'skirt_2.png'],
    [0, 54, 2, 'A shoe is more expensive than a balloon.wav', 'shoe_2.png', 'balloon_2.png'],
    [0, 55, 2, 'participant', 'trumpet_2.png', 'rubber_2.png'],
    [0, 56, 2, 'A candle is more expensive than a uhm sandwich.wav', 'candle_2.png', 'sandwich_2.png'],
    [0, 57, 2, 'participant', 'Sledge_2.png', 'hammer_2.png'],
    [0, 58, 2, 'A knife is cheaper than a lorry.wav', 'knife_2.png', 'lorry_2.png'],
    [0, 59, 2, 'participant', 'violin_2.png', 'tie_2.png'],
    [0, 60, 2, 'A wallet is more expensive than a dustbin.wav', 'wallet_2.png', 'dustbin_2.png'],
    [0, 61, 2, 'participant', 'apple_2.png', 'umbrella_2.png'],
    [0, 62, 2, 'A chair is cheaper than a violin.wav', 'chair_2.png', 'volleyball_2.png'],
    [0, 63, 2, 'participant', 'wallet_2.png', 'barbecue_2.png'],
    [0, 64, 2, 'A lorry is more expensive than a blanket.wav', 'lorry_2.png', 'blanket_2.png'],
    [0, 65, 2, 'participant', 'clock_2.png', 'apple_2.png'],
    [0, 66, 2, 'A dustbin is cheaper than a radio.wav', 'dustbin_2.png', 'radio_2.png'],
    [0, 67, 2, 'participant', 'volleyball_2.png', 'toothbrush_2.png'],
    [0, 68, 2, 'A watermelon is uhm cheaper than a shoe (HES).wav', 'watermelon_2.png', 'shoe_2.png'],
    [0, 69, 2, 'participant', 'pencil_2.png', 'lorry_2.png'],
    [0, 70, 2, 'An umbrella is cheaper than a car.wav', 'umbrella_2.png', 'Car_2.png'],
    [0, 71, 2, 'participant', 'belt_2.png', 'dustbin_2.png'],
    [0, 72, 2, 'NEW - A pumpkin is cheaper than a UHM house (HES).wav', 'pumpkin_2.png', 'house_2.png'],
    [0, 73, 2, 'participant', 'carrot_2.png', 'watch_2.png'],
    [0, 74, 2, 'NEW - A torch is more expensive than a pencil.wav', 'torch_2.png', 'pencil_2.png'],
    [0, 75, 2, 'participant', 'umbrella_2.png', 'Car_2.png'],
    [0, 76, 2, 'NEW - A belt is more expensive than chips.wav', 'belt_2.png', 'chips_2.png'],
    [0, 77, 2, 'participant', 'banana_2.png', 'nail2_2.png'],
    [0, 78, 2, 'NEW_A lock is UHM cheaper than a bed (HES).wav', 'Lock_2.png', 'bed_2.png'],
    [0, 79, 2, 'participant', 'Plate_New_2.png', 'umbrella_2.png'],
    [0, 80, 2, 'NEW_A belt is cheaper than a torch.wav', 'belt_2.png', 'torch_2.png'],
    [0, 81, 2, 'participant', 'razor_2.png', 'bra_2.png'],
    [0, 82, 2, 'NEW_Chips are cheaper than cheese.wav', 'chips_2.png', 'Cheese_2.png'],
    [0, 83, 2, 'participant', 'bed_2.png', 'ashtray_2.png'],
    [0, 84, 2, 'NEW_A pumpkin is UHM more expensive than a tomato(HES).wav', 'pumpkin_2.png', 'tomato_2.png'],
    [0, 85, 2, 'participant', 'torch_2.png', 'barbecue_2.png'],
    [0, 86, 2, 'NEW - A car is UHM more expensive than a scarf (HES).wav', 'Car_2.png', 'scarf_2.png'],
    [0, 87, 2, 'participant', 'bicycle_2.png', 'chips_2.png'],
    [0, 88, 3, 'CORRECT A jumper is more expensive than breas.wav', 'jumper_2.png', 'bread_2.png'],
    [0, 89, 3, 'participant', 'toothbrush_2.png', 'brush_2.png'],
    [0, 90, 3, 'CORRECT A sweet is cheaper than a toothbrush.wav', 'sweet_2.png', 'toothbrush_2.png'],
    [0, 91, 3, 'participant', 'laptop_2.png', 'Globe_2.png'],
    [0, 92, 3, 'A pear is more expensive than a UHM button (HES).wav', 'pear_2.png', 'button_2.png'],
    [0, 93, 3, 'participant', 'scissors_2.png', 'Cheese_2.png'],
    [0, 94, 3, 'A fork is cheaper than a jumper.wav', 'fork_2.png', 'jumper_2.png'],
    [0, 95, 3, 'participant', 'key_2.png', 'Plate_New_2.png'],
    [0, 96, 3, 'A fork is more expensive than a sweet.wav', 'fork_2.png', 'sweet_2.png'],
    [0, 97, 3, 'participant', 'chair_2.png', 'perfume_2.png'],
    [0, 98, 3, 'A hat is more expensive than a UHM blanket (HES).wav', 'hat_2.png', 'blanket_2.png'],
    [0, 99, 3, 'participant', 'jumper_2.png', 'guitar_2.png'],
    [0, 100, 3, 'A barbecue is more expensive than perfume.wav', 'barbecue_2.png', 'perfume_2.png'],
    [0, 101, 3, 'participant', 'sweet_2.png', 'balloon_2.png'],
    [0, 102, 3, 'A hat is cheaper than a shopping trolley.wav', 'hat_2.png', 'Shopping Trolley_2.png'],
    [0, 103, 3, 'participant', 'watch_2.png', 'glasses_2.png'],
    [0, 104, 3, 'An aubergine is cheaper than a spoon.wav', 'Aubergine_2.png', 'spoon_2.png'],
    [0, 105, 3, 'participant', 'laptop_2.png', 'drum_2.png'],
    [0, 106, 3, 'A wallet is UHM cheaper than a mixer (HES).wav', 'wallet_2.png', 'mixer_2.png'],
    [0, 107, 3, 'participant', 'brush_2.png', 'basket_2.png'],
    [0, 108, 3, 'A shopping trolley is more expensive than a whistle.wav', 'Shopping Trolley_2.png', 'whistle_2.png'],
    [0, 109, 3, 'participant', 'pizza_2.png', 'lamp_2.png'],
    [0, 110, 3, 'A calculator is more expensive than an aubergine.wav', 'calculator_2.png', 'Aubergine_2.png'],
    [0, 111, 3, 'participant', 'Cheese_2.png', 'newspaper_2.png'],
    [0, 112, 3, 'A banana is cheaper than bread.wav', 'banana_2.png', 'bread_2.png'],
    [0, 113, 3, 'participant', 'trumpet_2.png', 'Shopping Trolley_2.png'],
    [0, 114, 3, 'A lamp is UHM cheaper than a bench (HES).wav', 'lamp_2.png', 'bench_2.png'],
    [0, 115, 3, 'participant', 'Aubergine_2.png', 'skirt_2.png'],
    [0, 116, 3, 'A pear is cheaper than a postbox.wav', 'pear_2.png', 'Postbox_2.png'],
    [0, 117, 3, 'participant', 'key_2.png', 'egg_2.png'],
    [0, 118, 3, 'A bicyle is more expensive than a plaster.wav', 'bicycle_2.png', 'pflaster_2.png'],
    [0, 119, 3, 'participant', 'mixer_2.png', 'ashtray_2.png'],
    [0, 120, 3, 'A candle is more expensive than a UHM pencil (HES).wav', 'candle_2.png', 'pencil_2.png'],
    [0, 121, 3, 'participant', 'sandwich_2.png', 'book_2.png'],
    [0, 122, 3, 'A postbox is more expensive than a knife.wav', 'Postbox_2.png', 'knife_2.png'],
    [0, 123, 3, 'participant', 'lipstick_2.png', 'suitcase_2.png'],
    [0, 124, 3, 'A plaster is cheaper than a key.wav', 'pflaster_2.png', 'key_2.png'],
    [0, 125, 3, 'participant', 'trumpet_2.png', 'newspaper_2.png'],
    [0, 126, 3, 'A knife is cheaper than a cake.wav', 'knife_2.png', 'cake_2.png'],
    [0, 127, 3, 'participant', 'bicycle_2.png', 'Postbox_2.png'],
    [0, 128, 3, 'A pizza is more expensive than a UHM whistle (HES).wav', 'pizza_2.png', 'whistle_2.png'],
    [0, 129, 3, 'participant', 'apple_2.png', 'pflaster_2.png'],
    [0, 130, 3, 'A nappy is more expensive than a tomato.wav', 'Nappy_2.png', 'tomato_2.png'],
    [0, 131, 3, 'participant', 'pillow_2.png', 'guitar_2.png'],
    [0, 132, 3, 'A pillow is more expensive than a tin.wav', 'pillow_2.png', 'Tin_2.png'],
    [0, 133, 3, 'participant', 'carrot_2.png', 'pumpkin_2.png'],
    [0, 134, 3, 'A newspaper is uhm cheaper than a clock (HES).wav', 'newspaper_2.png', 'clock_2.png'],
    [0, 135, 3, 'participant', 'tent_2.png', 'tomato_2.png'],
    [0, 136, 3, 'An egg is cheaper than a nappy.wav', 'egg_2.png', 'Nappy_2.png'],
    [0, 137, 3, 'participant', 'fork_2.png', 'Car_2.png'],
    [0, 138, 3, 'A tin is cheaper than a guitar.wav', 'Tin_2.png', 'guitar_2.png'],
    [0, 139, 3, 'participant', 'Globe_2.png', 'bread_2.png'],
    [0, 140, 3, 'A hammer is more expensive than a carrot.wav', 'hammer_2.png', 'carrot_2.png'],
    [0, 141, 3, 'participant', 'Nappy_2.png', 'shoe_2.png'],
    [0, 142, 3, 'A lipstick is uhm cheaper than a radio.wav', 'lipstick_2.png', 'radio_2.png'],
    [0, 143, 3, 'participant', 'blanket_2.png', 'Tin_2.png']
  ],

  // 1: List1 written sentences (cheap + expensive) Complete.docx
  [
    [1, 0, 1, 'A bra is more expensive than a book.wav', 'bra_2.png', 'book_2.png'],
    [1, 1, 1, 'participant', 'pizza_2.png', 'suitcase_2.png'],
    [1, 2, 1, 'An iron is cheaper than a telly.wav', 'iron_2.png', 'Telly_2.png'],
    [1, 3, 1, 'participant', 'violin_2.png', 'tent_2.png'],
    [1, 4, 1, 'A barbeque is more expensive than a biscuit.wav', 'barbecue_2.png', 'biscuit_2.png'],
    [1, 5, 1, 'participant', 'pear_2.png', 'lamp_2.png'],
    [1, 6, 1, 'A nail is cheaper than a spoon.wav', 'nail2_2.png', 'spoon_2.png'],
    [1, 7, 1, 'participant', 'hat_2.png', 'candle_2.png'],
    [1, 8, 1, 'block 8, sentence -01.wav', 'Telly_2.png', 'apple_2.png'],
    [1, 9, 1, 'participant', 'banana_2.png', 'umbrella_2.png'],
    [1, 10, 1, 'block 8, sentence -02.wav', 'biscuit_2.png', 'ashtray_2.png'],
    [1, 11, 1, 'participant', 'balloon_2.png', 'lemon_2.png'],
    [1, 12, 1, 'A banana is cheaper than a globe.wav', 'banana_2.png', 'Globe_2.png'],
    [1, 13, 1, 'participant', 'pillow_2.png', 'Telly_2.png'],
    [1, 14, 1, 'block 8, sentence -04.wav', 'chair_2.png', 'Lock_2.png'],
    [1, 15, 1, 'participant', 'scissors_2.png', 'biscuit_2.png'],
    [1, 16, 1, 'block 8, sentence -05.wav', 'Refrigerator_2.png', 'brush_2.png'],
    [1, 17, 1, 'participant', 'volleyball_2.png', 'button_2.png'],
    [1, 18, 1, 'A belt is cheaper than a rucksack.wav', 'belt_2.png', 'Rucksack_2.png'],
    [1, 19, 1, 'participant', 'lemon_2.png', 'bra_2.png'],
    [1, 20, 1, 'A basket is more expensive than a book.wav', 'basket_2.png', 'book_2.png'],
    [1, 21, 1, 'participant', 'iron_2.png', 'scarf_2.png'],
    [1, 22, 1, 'A watermelon is cheaper than a refrigerator.wav', 'watermelon_2.png', 'Refrigerator_2.png'],
    [1, 23, 1, 'participant', 'clock_2.png', 'iron_2.png'],
    [1, 24, 1, 'A rucksack is more expensive than a lemon.wav', 'Rucksack_2.png', 'lemon_2.png'],
    [1, 25, 1, 'participant', 'scarf_2.png', 'calculator_2.png'],
    [1, 26, 1, 'A razor is more expensive than a watermelon.wav', 'razor_2.png', 'watermelon_2.png'],
    [1, 27, 1, 'participant', 'Refrigerator_2.png', 'bench_2.png'],
    [1, 28, 1, 'Scissors are more expensive than bread.wav', 'scissors_2.png', 'bread_2.png'],
    [1, 29, 1, 'participant', 'glasses_2.png', 'Rucksack_2.png'],
    [1, 30, 1, 'A hoover is more expensive than a tie.wav', 'hoover_2.png', 'tie_2.png'],
    [1, 31, 1, 'participant', 'sandwich_2.png', 'perfume_2.png'],
    [1, 32, 1, 'An aeroplane is more expensive than a nail.wav', 'Aeroplane_2.png', 'nail2_2.png'],
    [1, 33, 1, 'participant', 'camera_2.png', 'laptop_2.png'],
    [1, 34, 1, 'A watch is more expensive than a drum.wav', 'watch_2.png', 'drum_2.png'],
    [1, 35, 1, 'participant', 'apple_2.png', 'house_2.png'],
    [1, 36, 1, 'A hammer is cheaper than a hoover.wav', 'hammer_2.png', 'hoover_2.png'],
    [1, 37, 1, 'participant', 'suitcase_2.png', 'house_2.png'],
    [1, 38, 1, 'A cake a is cheaper than an aeroplane.wav', 'cake_2.png', 'Aeroplane_2.png'],
    [1, 39, 1, 'participant', 'volleyball_2.png', 'calculator_2.png'],
    [1, 40, 1, 'A mixer is more expensive than a skirt.wav', 'mixer_2.png', 'skirt_2.png'],
    [1, 41, 1, 'participant', 'hoover_2.png', 'bench_2.png'],
    [1, 42, 1, 'A pencil is cheaper than a radio.wav', 'pencil_2.png', 'radio_2.png'],
    [1, 43, 1, 'participant', 'Aeroplane_2.png', 'spoon_2.png'],
    [1, 44, 2, 'A lock is more expensive than a rubber.wav', 'Lock_2.png', 'rubber_2.png'],
    [1, 45, 2, 'participant', 'razor_2.png', 'glasses_2.png'],
    [1, 46, 2, 'A sledge is more expensive than a whistle.wav', 'Sledge_2.png', 'whistle_2.png'],
    [1, 47, 2, 'participant', 'camera_2.png', 'basket_2.png'],
    [1, 48, 2, 'A cake is cheaper than a camera.wav', 'cake_2.png', 'camera_2.png'],
    [1, 49, 2, 'participant', 'drum_2.png', 'lipstick_2.png'],
    [1, 50, 2, 'A rubber is cheaper than a tent.wav', 'rubber_2.png', 'tent_2.png'],
    [1, 51, 2, 'participant', 'egg_2.png', 'button_2.png'],
    [1, 52, 2, 'A tie is cheaper than a sledge.wav', 'tie_2.png', 'Sledge_2.png'],
    [1, 53, 2, 'participant', 'bed_2.png', 'skirt_2.png'],
    [1, 54, 2, 'A shoe is more expensive than a balloon.wav', 'shoe_2.png', 'balloon_2.png'],
    [1, 55, 2, 'participant', 'trumpet_2.png', 'rubber_2.png'],
    [1, 56, 2, 'A candle is more expensive than a sandwich.wav', 'candle_2.png', 'sandwich_2.png'],
    [1, 57, 2, 'participant', 'Sledge_2.png', 'hammer_2.png'],
    [1, 58, 2, 'A knife is cheaper than a lorry.wav', 'knife_2.png', 'lorry_2.png'],
    [1, 59, 2, 'participant', 'violin_2.png', 'tie_2.png'],
    [1, 60, 2, 'A wallet is more expensive than a dustbin.wav', 'wallet_2.png', 'dustbin_2.png'],
    [1, 61, 2, 'participant', 'apple_2.png', 'umbrella_2.png'],
    [1, 62, 2, 'A chair is cheaper than a violin.wav', 'chair_2.png', 'volleyball_2.png'],
    [1, 63, 2, 'participant', 'wallet_2.png', 'barbecue_2.png'],
    [1, 64, 2, 'A lorry is more expensive than a blanket.wav', 'lorry_2.png', 'blanket_2.png'],
    [1, 65, 2, 'participant', 'clock_2.png', 'apple_2.png'],
    [1, 66, 2, 'A dustbin is cheaper than a radio.wav', 'dustbin_2.png', 'radio_2.png'],
    [1, 67, 2, 'participant', 'volleyball_2.png', 'toothbrush_2.png'],
    [1, 68, 2, 'A watermelon is cheaper than a shoe.wav', 'watermelon_2.png', 'shoe_2.png'],
    [1, 69, 2, 'participant', 'pencil_2.png', 'lorry_2.png'],
    [1, 70, 2, 'An umbrella is cheaper than a car.wav', 'umbrella_2.png', 'Car_2.png'],
    [1, 71, 2, 'participant', 'belt_2.png', 'dustbin_2.png'],
    [1, 72, 2, 'A pumpkin is cheaper than a house.wav', 'pumpkin_2.png', 'house_2.png'],
    [1, 73, 2, 'participant', 'carrot_2.png', 'watch_2.png'],
    [1, 74, 2, 'NEW - A torch is more expensive than a pencil.wav', 'torch_2.png', 'pencil_2.png'],
    [1, 75, 2, 'participant', 'umbrella_2.png', 'Car_2.png'],
    [1, 76, 2, 'NEW - A belt is more expensive than chips.wav', 'belt_2.png', 'chips_2.png'],
    [1, 77, 2, 'participant', 'banana_2.png', 'nail2_2.png'],
    [1, 78, 2, 'A lock is cheaper than a bed.wav', 'Lock_2.png', 'bed_2.png'],
    [1, 79, 2, 'participant', 'Plate_New_2.png', 'umbrella_2.png'],
    [1, 80, 2, 'NEW_A belt is cheaper than a torch.wav', 'belt_2.png', 'torch_2.png'],
    [1, 81, 2, 'participant', 'razor_2.png', 'bra_2.png'],
    [1, 82, 2, 'NEW_Chips are cheaper than cheese.wav', 'chips_2.png', 'Cheese_2.png'],
    [1, 83, 2, 'participant', 'bed_2.png', 'ashtray_2.png'],
    [1, 84, 2, 'A pumpkin is more expensive than a tomato.wav', 'pumpkin_2.png', 'tomato_2.png'],
    [1, 85, 2, 'participant', 'torch_2.png', 'barbecue_2.png'],
    [1, 86, 2, 'A car is more expensive than a scarf.wav', 'Car_2.png', 'scarf_2.png'],
    [1, 87, 2, 'participant', 'bicycle_2.png', 'chips_2.png'],
    [1, 88, 3, 'CORRECT A jumper is more expensive than breas.wav', 'jumper_2.png', 'bread_2.png'],
    [1, 89, 3, 'participant', 'toothbrush_2.png', 'brush_2.png'],
    [1, 90, 3, 'CORRECT A sweet is cheaper than a toothbrush.wav', 'sweet_2.png', 'toothbrush_2.png'],
    [1, 91, 3, 'participant', 'laptop_2.png', 'Globe_2.png'],
    [1, 92, 3, 'A pear is more expensive than a button.wav', 'pear_2.png', 'button_2.png'],
    [1, 93, 3, 'participant', 'scissors_2.png', 'Cheese_2.png'],
    [1, 94, 3, 'A fork is cheaper than a jumper.wav', 'fork_2.png', 'jumper_2.png'],
    [1, 95, 3, 'participant', 'key_2.png', 'Plate_New_2.png'],
    [1, 96, 3, 'A fork is more expensive than a sweet.wav', 'fork_2.png', 'sweet_2.png'],
    [1, 97, 3, 'participant', 'chair_2.png', 'perfume_2.png'],
    [1, 98, 3, 'A hat is more expensive than a blanket.wav', 'hat_2.png', 'blanket_2.png'],
    [1, 99, 3, 'participant', 'jumper_2.png', 'guitar_2.png'],
    [1, 100, 3, 'A barbecue is more expensive than perfume.wav', 'barbecue_2.png', 'perfume_2.png'],
    [1, 101, 3, 'participant', 'sweet_2.png', 'balloon_2.png'],
    [1, 102, 3, 'A hat is cheaper than a shopping trolley.wav', 'hat_2.png', 'Shopping Trolley_2.png'],
    [1, 103, 3, 'participant', 'watch_2.png', 'glasses_2.png'],
    [1, 104, 3, 'An aubergine is cheaper than a spoon.wav', 'Aubergine_2.png', 'spoon_2.png'],
    [1, 105, 3, 'participant', 'laptop_2.png', 'drum_2.png'],
    [1, 106, 3, 'A wallet is cheaper than a mixer.wav', 'wallet_2.png', 'mixer_2.png'],
    [1, 107, 3, 'participant', 'brush_2.png', 'basket_2.png'],
    [1, 108, 3, 'A shopping trolley is more expensive than a whistle.wav', 'Shopping Trolley_2.png', 'whistle_2.png'],
    [1, 109, 3, 'participant', 'pizza_2.png', 'lamp_2.png'],
    [1, 110, 3, 'A calculator is more expensive than an aubergine.wav', 'calculator_2.png', 'Aubergine_2.png'],
    [1, 111, 3, 'participant', 'Cheese_2.png', 'newspaper_2.png'],
    [1, 112, 3, 'A banana is cheaper than bread.wav', 'banana_2.png', 'bread_2.png'],
    [1, 113, 3, 'participant', 'trumpet_2.png', 'Shopping Trolley_2.png'],
    [1, 114, 3, 'A lamp is cheaper than a bench.wav', 'lamp_2.png', 'bench_2.png'],
    [1, 115, 3, 'participant', 'Aubergine_2.png', 'skirt_2.png'],
    [1, 116, 3, 'A pear is cheaper than a postbox.wav', 'pear_2.png', 'Postbox_2.png'],
    [1, 117, 3, 'participant', 'key_2.png', 'egg_2.png'],
    [1, 118, 3, 'A bicyle is more expensive than a plaster.wav', 'bicycle_2.png', 'pflaster_2.png'],
    [1, 119, 3, 'participant', 'mixer_2.png', 'ashtray_2.png'],
    [1, 120, 3, 'A candle is more expensive than a pencil.wav', 'candle_2.png', 'pencil_2.png'],
    [1, 121, 3, 'participant', 'sandwich_2.png', 'book_2.png'],
    [1, 122, 3, 'A postbox is more expensive than a knife.wav', 'Postbox_2.png', 'knife_2.png'],
    [1, 123, 3, 'participant', 'lipstick_2.png', 'suitcase_2.png'],
    [1, 124, 3, 'A plaster is cheaper than a key.wav', 'pflaster_2.png', 'key_2.png'],
    [1, 125, 3, 'participant', 'trumpet_2.png', 'newspaper_2.png'],
    [1, 126, 3, 'A knife is cheaper than a cake.wav', 'knife_2.png', 'cake_2.png'],
    [1, 127, 3, 'participant', 'bicycle_2.png', 'Postbox_2.png'],
    [1, 128, 3, 'A pizza is more expensive than a whistle.wav', 'pizza_2.png', 'whistle_2.png'],
    [1, 129, 3, 'participant', 'apple_2.png', 'pflaster_2.png'],
    [1, 130, 3, 'A nappy is more expensive than a tomato.wav', 'Nappy_2.png', 'tomato_2.png'],
    [1, 131, 3, 'participant', 'pillow_2.png', 'guitar_2.png'],
    [1, 132, 3, 'A pillow is more expensive than a tin.wav', 'pillow_2.png', 'Tin_2.png'],
    [1, 133, 3, 'participant', 'carrot_2.png', 'pumpkin_2.png'],
    [1, 134, 3, 'A newspaper is cheaper than a clock.wav', 'newspaper_2.png', 'clock_2.png'],
    [1, 135, 3, 'participant', 'tent_2.png', 'tomato_2.png'],
    [1, 136, 3, 'An egg is cheaper than a nappy.wav', 'egg_2.png', 'Nappy_2.png'],
    [1, 137, 3, 'participant', 'fork_2.png', 'Car_2.png'],
    [1, 138, 3, 'A tin is cheaper than a guitar.wav', 'Tin_2.png', 'guitar_2.png'],
    [1, 139, 3, 'participant', 'Globe_2.png', 'bread_2.png'],
    [1, 140, 3, 'A hammer is more expensive than a carrot.wav', 'hammer_2.png', 'carrot_2.png'],
    [1, 141, 3, 'participant', 'Nappy_2.png', 'shoe_2.png'],
    [1, 142, 3, 'A lipstick is cheaper than a radio.wav', 'lipstick_2.png', 'radio_2.png'],
    [1, 143, 3, 'participant', 'blanket_2.png', 'Tin_2.png']
  ],

  // 2: List2 hesitant written sentences (cheap + expensive) Complete.docx
  [
    [2, 0, 1, 'NEW - A pumpkin is cheaper than a UHM house (HES).wav', 'pumpkin_2.png', 'house_2.png'],
    [2, 1, 1, 'participant', 'carrot_2.png', 'watch_2.png'],
    [2, 2, 1, 'NEW - A torch is more expensive than a pencil.wav', 'torch_2.png', 'pencil_2.png'],
    [2, 3, 1, 'participant', 'umbrella_2.png', 'Car_2.png'],
    [2, 4, 1, 'NEW - A belt is more expensive than chips.wav', 'belt_2.png', 'chips_2.png'],
    [2, 5, 1, 'participant', 'banana_2.png', 'nail2_2.png'],
    [2, 6, 1, 'NEW_A lock is UHM cheaper than a bed (HES).wav', 'Lock_2.png', 'bed_2.png'],
    [2, 7, 1, 'participant', 'Plate_New_2.png', 'umbrella_2.png'],
    [2, 8, 1, 'NEW_A belt is cheaper than a torch.wav', 'belt_2.png', 'torch_2.png'],
    [2, 9, 1, 'participant', 'razor_2.png', 'bra_2.png'],
    [2, 10, 1, 'NEW_Chips are cheaper than cheese.wav', 'chips_2.png', 'Cheese_2.png'],
    [2, 11, 1, 'participant', 'bed_2.png', 'ashtray_2.png'],
    [2, 12, 1, 'NEW_A pumpkin is UHM more expensive than a tomato(HES).wav', 'pumpkin_2.png', 'tomato_2.png'],
    [2, 13, 1, 'participant', 'torch_2.png', 'barbecue_2.png'],
    [2, 14, 1, 'NEW - A car is UHM more expensive than a scarf (HES).wav', 'Car_2.png', 'scarf_2.png'],
    [2, 15, 1, 'participant', 'bicycle_2.png', 'chips_2.png'],
    [2, 16, 1, 'CORRECT A jumper is more expensive than breas.wav', 'jumper_2.png', 'bread_2.png'],
    [2, 17, 1, 'participant', 'toothbrush_2.png', 'brush_2.png'],
    [2, 18, 1, 'CORRECT A sweet is cheaper than a toothbrush.wav', 'sweet_2.png', 'toothbrush_2.png'],
    [2, 19, 1, 'participant', 'laptop_2.png', 'Globe_2.png'],
    [2, 20, 1, 'A pear is more expensive than a UHM button (HES).wav', 'pear_2.png', 'button_2.png'],
    [2, 21, 1, 'participant', 'scissors_2.png', 'Cheese_2.png'],
    [2, 22, 1, 'A fork is cheaper than a jumper.wav', 'fork_2.png', 'jumper_2.png'],
    [2, 23, 1, 'participant', 'key_2.png', 'Plate_New_2.png'],
    [2, 24, 1, 'A fork is more expensive than a sweet.wav', 'fork_2.png', 'sweet_2.png'],
    [2, 25, 1, 'participant', 'chair_2.png', 'perfume_2.png'],
    [2, 26, 1, 'A hat is more expensive than a UHM blanket (HES).wav', 'hat_2.png', 'blanket_2.png'],
    [2, 27, 1, 'participant', 'jumper_2.png', 'guitar_2.png'],
    [2, 28, 1, 'A barbecue is more expensive than perfume.wav', 'barbecue_2.png', 'perfume_2.png'],
    [2, 29, 1, 'participant', 'sweet_2.png', 'balloon_2.png'],
    [2, 30, 1, 'A hat is cheaper than a shopping trolley.wav', 'hat_2.png', 'Shopping Trolley_2.png'],
    [2, 31, 1, 'participant', 'watch_2.png', 'glasses_2.png'],
    [2, 32, 1, 'An aubergine is cheaper than a spoon.wav', 'Aubergine_2.png', 'spoon_2.png'],
    [2, 33, 1, 'participant', 'laptop_2.png', 'drum_2.png'],
    [2, 34, 1, 'A wallet is UHM cheaper than a mixer (HES).wav', 'wallet_2.png', 'mixer_2.png'],
    [2, 35, 1, 'participant', 'brush_2.png', 'basket_2.png'],
    [2, 36, 1, 'A shopping trolley is more expensive than a whistle.wav', 'Shopping Trolley_2.png', 'whistle_2.png'],
    [2, 37, 1, 'participant', 'pizza_2.png', 'lamp_2.png'],
    [2, 38, 1, 'A calculator is more expensive than an aubergine.wav', 'calculator_2.png', 'Aubergine_2.png'],
    [2, 39, 1, 'participant', 'Cheese_2.png', 'newspaper_2.png'],
    [2, 40, 1, 'A banana is cheaper than bread.wav', 'banana_2.png', 'bread_2.png'],
    [2, 41, 1, 'participant', 'trumpet_2.png', 'Shopping Trolley_2.png'],
    [2, 42, 1, 'A lamp is UHM cheaper than a bench (HES).wav', 'lamp_2.png', 'bench_2.png'],
    [2, 43, 1, 'participant', 'Aubergine_2.png', 'skirt_2.png'],
    [2, 44, 2, 'A pear is cheaper than a postbox.wav', 'pear_2.png', 'Postbox_2.png'],
    [2, 45, 2, 'participant', 'key_2.png', 'egg_2.png'],
    [2, 46, 2, 'A bicyle is more expensive than a plaster.wav', 'bicycle_2.png', 'pflaster_2.png'],
    [2, 47, 2, 'participant', 'mixer_2.png', 'ashtray_2.png'],
    [2, 48, 2, 'A candle is more expensive than a UHM pencil (HES).wav', 'candle_2.png', 'pencil_2.png'],
    [2, 49, 2, 'participant', 'sandwich_2.png', 'book_2.png'],
    [2, 50, 2, 'A postbox is more expensive than a knife.wav', 'Postbox_2.png', 'knife_2.png'],
    [2, 51, 2, 'participant', 'lipstick_2.png', 'suitcase_2.png'],
    [2, 52, 2, 'A plaster is cheaper than a key.wav', 'pflaster_2.png', 'key_2.png'],
    [2, 53, 2, 'participant', 'trumpet_2.png', 'newspaper_2.png'],
    [2, 54, 2, 'A knife is cheaper than a cake.wav', 'knife_2.png', 'cake_2.png'],
    [2, 55, 2, 'participant', 'bicycle_2.png', 'Postbox_2.png'],
    [2, 56, 2, 'A pizza is more expensive than a UHM whistle (HES).wav', 'pizza_2.png', 'whistle_2.png'],
    [2, 57, 2, 'participant', 'apple_2.png', 'pflaster_2.png'],
    [2, 58, 2, 'A nappy is more expensive than a tomato.wav', 'Nappy_2.png', 'tomato_2.png'],
    [2, 59, 2, 'participant', 'pillow_2.png', 'guitar_2.png'],
    [2, 60, 2, 'A pillow is more expensive than a tin.wav', 'pillow_2.png', 'Tin_2.png'],
    [2, 61, 2, 'participant', 'carrot_2.png', 'pumpkin_2.png'],
    [2, 62, 2, 'A newspaper is uhm cheaper than a clock (HES).wav', 'newspaper_2.png', 'clock_2.png'],
    [2, 63, 2, 'participant', 'tent_2.png', 'tomato_2.png'],
    [2, 64, 2, 'An egg is cheaper than a nappy.wav', 'egg_2.png', 'Nappy_2.png'],
    [2, 65, 2, 'participant', 'fork_2.png', 'Car_2.png'],
    [2, 66, 2, 'A tin is cheaper than a guitar.wav', 'Tin_2.png', 'guitar_2.png'],
    [2, 67, 2, 'participant', 'Globe_2.png', 'bread_2.png'],
    [2, 68, 2, 'A hammer is more expensive than a carrot.wav', 'hammer_2.png', 'carrot_2.png'],
    [2, 69, 2, 'participant', 'Nappy_2.png', 'shoe_2.png'],
    [2, 70, 2, 'A lipstick is uhm cheaper than a radio.wav', 'lipstick_2.png', 'radio_2.png'],
    [2, 71, 2, 'participant', 'blanket_2.png', 'Tin_2.png'],
    [2, 72, 2, 'A bra is uhm more expensive than a book (HES).wav', 'bra_2.png', 'book_2.png'],
    [2, 73, 2, 'participant', 'pizza_2.png', 'suitcase_2.png'],
    [2, 74, 2, 'An iron is cheaper than a telly.wav', 'iron_2.png', 'Telly_2.png'],
    [2, 75, 2, 'participant', 'violin_2.png', 'tent_2.png'],
    [2, 76, 2, 'A barbeque is more expensive than a biscuit.wav', 'barbecue_2.png', 'biscuit_2.png'],
    [2, 77, 2, 'participant', 'pear_2.png', 'lamp_2.png'],
    [2, 78, 2, 'A nail is cheaper than a uhm spoon.wav', 'nail2_2.png', 'spoon_2.png'],
    [2, 79, 2, 'participant', 'hat_2.png', 'candle_2.png'],
    [2, 80, 2, 'block 8, sentence -01.wav', 'Telly_2.png', 'apple_2.png'],
    [2, 81, 2, 'participant', 'banana_2.png', 'umbrella_2.png'],
    [2, 82, 2, 'block 8, sentence -02.wav', 'biscuit_2.png', 'ashtray_2.png'],
    [2, 83, 2, 'participant', 'balloon_2.png', 'lemon_2.png'],
    [2, 84, 2, 'block 8, sentence -03.wav', 'banana_2.png', 'Globe_2.png'],
    [2, 85, 2, 'participant', 'pillow_2.png', 'Telly_2.png'],
    [2, 86, 2, 'block 8, sentence -04.wav', 'chair_2.png', 'Lock_2.png'],
    [2, 87, 2, 'participant', 'scissors_2.png', 'biscuit_2.png'],
    [2, 88, 3, 'block 8, sentence -05.wav', 'Refrigerator_2.png', 'brush_2.png'],
    [2, 89, 3, 'participant', 'volleyball_2.png', 'button_2.png'],
    [2, 90, 3, 'A belt is cheaper than a rucksack.wav', 'belt_2.png', 'Rucksack_2.png'],
    [2, 91, 3, 'participant', 'lemon_2.png', 'bra_2.png'],
    [2, 92, 3, 'A basket is UHM more expensive than a book (HES).wav', 'basket_2.png', 'book_2.png'],
    [2, 93, 3, 'participant', 'iron_2.png', 'scarf_2.png'],
    [2, 94, 3, 'A watermelon is cheaper than a refrigerator.wav', 'watermelon_2.png', 'Refrigerator_2.png'],
    [2, 95, 3, 'participant', 'clock_2.png', 'iron_2.png'],
    [2, 96, 3, 'A rucksack is more expensive than a lemon.wav', 'Rucksack_2.png', 'lemon_2.png'],
    [2, 97, 3, 'participant', 'scarf_2.png', 'calculator_2.png'],
    [2, 98, 3, 'A razor is  UHM more expensive than a watermelon (HES).wav', 'razor_2.png', 'watermelon_2.png'],
    [2, 99, 3, 'participant', 'Refrigerator_2.png', 'bench_2.png'],
    [2, 100, 3, 'Scissors are more expensive than bread.wav', 'scissors_2.png', 'bread_2.png'],
    [2, 101, 3, 'participant', 'glasses_2.png', 'Rucksack_2.png'],
    [2, 102, 3, 'A hoover is more expensive than a tie.wav', 'hoover_2.png', 'tie_2.png'],
    [2, 103, 3, 'participant', 'sandwich_2.png', 'perfume_2.png'],
    [2, 104, 3, 'An aeroplane is more expensive than a nail.wav', 'Aeroplane_2.png', 'nail2_2.png'],
    [2, 105, 3, 'participant', 'camera_2.png', 'laptop_2.png'],
    [2, 106, 3, 'A watch is more expensive than a uhm drum (HES).wav', 'watch_2.png', 'drum_2.png'],
    [2, 107, 3, 'participant', 'apple_2.png', 'house_2.png'],
    [2, 108, 3, 'A hammer is cheaper than a hoover.wav', 'hammer_2.png', 'hoover_2.png'],
    [2, 109, 3, 'participant', 'suitcase_2.png', 'house_2.png'],
    [2, 110, 3, 'A cake a is cheaper than an aeroplane.wav', 'cake_2.png', 'Aeroplane_2.png'],
    [2, 111, 3, 'participant', 'volleyball_2.png', 'calculator_2.png'],
    [2, 112, 3, 'A mixer is more expensive than a uhm skirt (HES).wav', 'mixer_2.png', 'skirt_2.png'],
    [2, 113, 3, 'participant', 'hoover_2.png', 'bench_2.png'],
    [2, 114, 3, 'A pencil is cheaper than a uhm radio.wav', 'pencil_2.png', 'radio_2.png'],
    [2, 115, 3, 'participant', 'Aeroplane_2.png', 'spoon_2.png'],
    [2, 116, 3, 'A lock is more expensive than a rubber.wav', 'Lock_2.png', 'rubber_2.png'],
    [2, 117, 3, 'participant', 'razor_2.png', 'glasses_2.png'],
    [2, 118, 3, 'A sledge is more expensive than a whistle.wav', 'Sledge_2.png', 'whistle_2.png'],
    [2, 119, 3, 'participant', 'camera_2.png', 'basket_2.png'],
    [2, 120, 3, 'A cake is cheaper than a camera.wav', 'cake_2.png', 'camera_2.png'],
    [2, 121, 3, 'participant', 'drum_2.png', 'lipstick_2.png'],
    [2, 122, 3, 'A rubber is cheaper than a tent.wav', 'rubber_2.png', 'tent_2.png'],
    [2, 123, 3, 'participant', 'egg_2.png', 'button_2.png'],
    [2, 124, 3, 'A tie is cheaper than a sledge.wav', 'tie_2.png', 'Sledge_2.png'],
    [2, 125, 3, 'participant', 'bed_2.png', 'skirt_2.png'],
    [2, 126, 3, 'A shoe is more expensive than a balloon.wav', 'shoe_2.png', 'balloon_2.png'],
    [2, 127, 3, 'participant', 'trumpet_2.png', 'rubber_2.png'],
    [2, 128, 3, 'A candle is more expensive than a uhm sandwich.wav', 'candle_2.png', 'sandwich_2.png'],
    [2, 129, 3, 'participant', 'Sledge_2.png', 'hammer_2.png'],
    [2, 130, 3, 'A knife is cheaper than a lorry.wav', 'knife_2.png', 'lorry_2.png'],
    [2, 131, 3, 'participant', 'violin_2.png', 'tie_2.png'],
    [2, 132, 3, 'A wallet is more expensive than a dustbin.wav', 'wallet_2.png', 'dustbin_2.png'],
    [2, 133, 3, 'participant', 'apple_2.png', 'umbrella_2.png'],
    [2, 134, 3, 'A chair is cheaper than a violin.wav', 'chair_2.png', 'violin_2.png'],
    [2, 135, 3, 'participant', 'wallet_2.png', 'barbecue_2.png'],
    [2, 136, 3, 'A lorry is more expensive than a blanket.wav', 'lorry_2.png', 'blanket_2.png'],
    [2, 137, 3, 'participant', 'clock_2.png', 'apple_2.png'],
    [2, 138, 3, 'A dustbin is cheaper than a radio.wav', 'dustbin_2.png', 'radio_2.png'],
    [2, 139, 3, 'participant', 'volleyball_2.png', 'toothbrush_2.png'],
    [2, 140, 3, 'A watermelon is uhm cheaper than a shoe (HES).wav', 'watermelon_2.png', 'shoe_2.png'],
    [2, 141, 3, 'participant', 'pencil_2.png', 'lorry_2.png'],
    [2, 142, 3, 'An umbrella is cheaper than a car.wav', 'umbrella_2.png', 'Car_2.png'],
    [2, 143, 3, 'participant', 'belt_2.png', 'dustbin_2.png']
  ],

  // 3: List2 written sentences (cheap + expensive) Complete.docx
  [
    [3, 0, 1, 'A pumpkin is cheaper than a house.wav', 'pumpkin_2.png', 'house_2.png'],
    [3, 1, 1, 'participant', 'carrot_2.png', 'watch_2.png'],
    [3, 2, 1, 'NEW - A torch is more expensive than a pencil.wav', 'torch_2.png', 'pencil_2.png'],
    [3, 3, 1, 'participant', 'umbrella_2.png', 'Car_2.png'],
    [3, 4, 1, 'NEW - A belt is more expensive than chips.wav', 'belt_2.png', 'chips_2.png'],
    [3, 5, 1, 'participant', 'banana_2.png', 'nail2_2.png'],
    [3, 6, 1, 'A lock is cheaper than a bed.wav', 'Lock_2.png', 'bed_2.png'],
    [3, 7, 1, 'participant', 'Plate_New_2.png', 'umbrella_2.png'],
    [3, 8, 1, 'NEW_A belt is cheaper than a torch.wav', 'belt_2.png', 'torch_2.png'],
    [3, 9, 1, 'participant', 'razor_2.png', 'bra_2.png'],
    [3, 10, 1, 'NEW_Chips are cheaper than cheese.wav', 'chips_2.png', 'Cheese_2.png'],
    [3, 11, 1, 'participant', 'bed_2.png', 'ashtray_2.png'],
    [3, 12, 1, 'A pumpkin is more expensive than a tomato.wav', 'pumpkin_2.png', 'tomato_2.png'],
    [3, 13, 1, 'participant', 'torch_2.png', 'barbecue_2.png'],
    [3, 14, 1, 'A car is more expensive than a scarf.wav', 'Car_2.png', 'scarf_2.png'],
    [3, 15, 1, 'participant', 'bicycle_2.png', 'chips_2.png'],
    [3, 16, 1, 'CORRECT A jumper is more expensive than breas.wav', 'jumper_2.png', 'bread_2.png'],
    [3, 17, 1, 'participant', 'toothbrush_2.png', 'brush_2.png'],
    [3, 18, 1, 'CORRECT A sweet is cheaper than a toothbrush.wav', 'sweet_2.png', 'toothbrush_2.png'],
    [3, 19, 1, 'participant', 'laptop_2.png', 'Globe_2.png'],
    [3, 20, 1, 'A pear is more expensive than a button.wav', 'pear_2.png', 'button_2.png'],
    [3, 21, 1, 'participant', 'scissors_2.png', 'Cheese_2.png'],
    [3, 22, 1, 'A fork is cheaper than a jumper.wav', 'fork_2.png', 'jumper_2.png'],
    [3, 23, 1, 'participant', 'key_2.png', 'Plate_New_2.png'],
    [3, 24, 1, 'A fork is more expensive than a sweet.wav', 'fork_2.png', 'sweet_2.png'],
    [3, 25, 1, 'participant', 'chair_2.png', 'perfume_2.png'],
    [3, 26, 1, 'A hat is more expensive than a blanket.wav', 'hat_2.png', 'blanket_2.png'],
    [3, 27, 1, 'participant', 'jumper_2.png', 'guitar_2.png'],
    [3, 28, 1, 'A barbecue is more expensive than perfume.wav', 'barbecue_2.png', 'perfume_2.png'],
    [3, 29, 1, 'participant', 'sweet_2.png', 'balloon_2.png'],
    [3, 30, 1, 'A hat is cheaper than a shopping trolley.wav', 'hat_2.png', 'Shopping Trolley_2.png'],
    [3, 31, 1, 'participant', 'watch_2.png', 'glasses_2.png'],
    [3, 32, 1, 'An aubergine is cheaper than a spoon.wav', 'Aubergine_2.png', 'spoon_2.png'],
    [3, 33, 1, 'participant', 'laptop_2.png', 'drum_2.png'],
    [3, 34, 1, 'A wallet is cheaper than a mixer.wav', 'wallet_2.png', 'mixer_2.png'],
    [3, 35, 1, 'participant', 'brush_2.png', 'basket_2.png'],
    [3, 36, 1, 'A shopping trolley is more expensive than a whistle.wav', 'Shopping Trolley_2.png', 'whistle_2.png'],
    [3, 37, 1, 'participant', 'pizza_2.png', 'lamp_2.png'],
    [3, 38, 1, 'A calculator is more expensive than an aubergine.wav', 'calculator_2.png', 'Aubergine_2.png'],
    [3, 39, 1, 'participant', 'Cheese_2.png', 'newspaper_2.png'],
    [3, 40, 1, 'A banana is cheaper than bread.wav', 'banana_2.png', 'bread_2.png'],
    [3, 41, 1, 'participant', 'trumpet_2.png', 'Shopping Trolley_2.png'],
    [3, 42, 1, 'A lamp is cheaper than a bench.wav', 'lamp_2.png', 'bench_2.png'],
    [3, 43, 1, 'participant', 'Aubergine_2.png', 'skirt_2.png'],
    [3, 44, 2, 'A pear is cheaper than a postbox.wav', 'pear_2.png', 'Postbox_2.png'],
    [3, 45, 2, 'participant', 'key_2.png', 'egg_2.png'],
    [3, 46, 2, 'A bicyle is more expensive than a plaster.wav', 'bicycle_2.png', 'pflaster_2.png'],
    [3, 47, 2, 'participant', 'mixer_2.png', 'ashtray_2.png'],
    [3, 48, 2, 'A candle is more expensive than a pencil.wav', 'candle_2.png', 'pencil_2.png'],
    [3, 49, 2, 'participant', 'sandwich_2.png', 'book_2.png'],
    [3, 50, 2, 'A postbox is more expensive than a knife.wav', 'Postbox_2.png', 'knife_2.png'],
    [3, 51, 2, 'participant', 'lipstick_2.png', 'suitcase_2.png'],
    [3, 52, 2, 'A plaster is cheaper than a key.wav', 'pflaster_2.png', 'key_2.png'],
    [3, 53, 2, 'participant', 'trumpet_2.png', 'newspaper_2.png'],
    [3, 54, 2, 'A knife is cheaper than a cake.wav', 'knife_2.png', 'cake_2.png'],
    [3, 55, 2, 'participant', 'bicycle_2.png', 'Postbox_2.png'],
    [3, 56, 2, 'A pizza is more expensive than a whistle.wav', 'pizza_2.png', 'whistle_2.png'],
    [3, 57, 2, 'participant', 'apple_2.png', 'pflaster_2.png'],
    [3, 58, 2, 'A nappy is more expensive than a tomato.wav', 'Nappy_2.png', 'tomato_2.png'],
    [3, 59, 2, 'participant', 'pillow_2.png', 'guitar_2.png'],
    [3, 60, 2, 'A pillow is more expensive than a tin.wav', 'pillow_2.png', 'Tin_2.png'],
    [3, 61, 2, 'participant', 'carrot_2.png', 'pumpkin_2.png'],
    [3, 62, 2, 'A newspaper is cheaper than a clock.wav', 'newspaper_2.png', 'clock_2.png'],
    [3, 63, 2, 'participant', 'tent_2.png', 'tomato_2.png'],
    [3, 64, 2, 'An egg is cheaper than a nappy.wav', 'egg_2.png', 'Nappy_2.png'],
    [3, 65, 2, 'participant', 'fork_2.png', 'Car_2.png'],
    [3, 66, 2, 'A tin is cheaper than a guitar.wav', 'Tin_2.png', 'guitar_2.png'],
    [3, 67, 2, 'participant', 'Globe_2.png', 'bread_2.png'],
    [3, 68, 2, 'A hammer is more expensive than a carrot.wav', 'hammer_2.png', 'carrot_2.png'],
    [3, 69, 2, 'participant', 'Nappy_2.png', 'shoe_2.png'],
    [3, 70, 2, 'A lipstick is cheaper than a radio.wav', 'lipstick_2.png', 'radio_2.png'],
    [3, 71, 2, 'participant', 'blanket_2.png', 'Tin_2.png'],
    [3, 72, 2, 'A bra is more expensive than a book.wav', 'bra_2.png', 'book_2.png'],
    [3, 73, 2, 'participant', 'pizza_2.png', 'suitcase_2.png'],
    [3, 74, 2, 'An iron is cheaper than a telly.wav', 'iron_2.png', 'Telly_2.png'],
    [3, 75, 2, 'participant', 'violin_2.png', 'tent_2.png'],
    [3, 76, 2, 'A barbeque is more expensive than a biscuit.wav', 'barbecue_2.png', 'biscuit_2.png'],
    [3, 77, 2, 'participant', 'pear_2.png', 'lamp_2.png'],
    [3, 78, 2, 'A nail is cheaper than a spoon.wav', 'nail2_2.png', 'spoon_2.png'],
    [3, 79, 2, 'participant', 'hat_2.png', 'candle_2.png'],
    [3, 80, 2, 'block 8, sentence -01.wav', 'Telly_2.png', 'apple_2.png'],
    [3, 81, 2, 'participant', 'banana_2.png', 'umbrella_2.png'],
    [3, 82, 2, 'block 8, sentence -02.wav', 'biscuit_2.png', 'ashtray_2.png'],
    [3, 83, 2, 'participant', 'balloon_2.png', 'lemon_2.png'],
    [3, 84, 2, 'A banana is cheaper than a globe.wav', 'banana_2.png', 'Globe_2.png'],
    [3, 85, 2, 'participant', 'pillow_2.png', 'Telly_2.png'],
    [3, 86, 2, 'block 8, sentence -04.wav', 'chair_2.png', 'Lock_2.png'],
    [3, 87, 2, 'participant', 'scissors_2.png', 'biscuit_2.png'],
    [3, 88, 3, 'block 8, sentence -05.wav', 'Refrigerator_2.png', 'brush_2.png'],
    [3, 89, 3, 'participant', 'volleyball_2.png', 'button_2.png'],
    [3, 90, 3, 'A belt is cheaper than a rucksack.wav', 'belt_2.png', 'Rucksack_2.png'],
    [3, 91, 3, 'participant', 'lemon_2.png', 'bra_2.png'],
    [3, 92, 3, 'A basket is more expensive than a book.wav', 'basket_2.png', 'book_2.png'],
    [3, 93, 3, 'participant', 'iron_2.png', 'scarf_2.png'],
    [3, 94, 3, 'A watermelon is cheaper than a refrigerator.wav', 'watermelon_2.png', 'Refrigerator_2.png'],
    [3, 95, 3, 'participant', 'clock_2.png', 'iron_2.png'],
    [3, 96, 3, 'A rucksack is more expensive than a lemon.wav', 'Rucksack_2.png', 'lemon_2.png'],
    [3, 97, 3, 'participant', 'scarf_2.png', 'calculator_2.png'],
    [3, 98, 3, 'A razor is more expensive than a watermelon.wav', 'razor_2.png', 'watermelon_2.png'],
    [3, 99, 3, 'participant', 'Refrigerator_2.png', 'bench_2.png'],
    [3, 100, 3, 'Scissors are more expensive than bread.wav', 'scissors_2.png', 'bread_2.png'],
    [3, 101, 3, 'participant', 'glasses_2.png', 'Rucksack_2.png'],
    [3, 102, 3, 'A hoover is more expensive than a tie.wav', 'hoover_2.png', 'tie_2.png'],
    [3, 103, 3, 'participant', 'sandwich_2.png', 'perfume_2.png'],
    [3, 104, 3, 'An aeroplane is more expensive than a nail.wav', 'Aeroplane_2.png', 'nail2_2.png'],
    [3, 105, 3, 'participant', 'camera_2.png', 'laptop_2.png'],
    [3, 106, 3, 'A watch is more expensive than a drum.wav', 'watch_2.png', 'drum_2.png'],
    [3, 107, 3, 'participant', 'apple_2.png', 'house_2.png'],
    [3, 108, 3, 'A hammer is cheaper than a hoover.wav', 'hammer_2.png', 'hoover_2.png'],
    [3, 109, 3, 'participant', 'suitcase_2.png', 'house_2.png'],
    [3, 110, 3, 'A cake a is cheaper than an aeroplane.wav', 'cake_2.png', 'Aeroplane_2.png'],
    [3, 111, 3, 'participant', 'volleyball_2.png', 'calculator_2.png'],
    [3, 112, 3, 'A mixer is more expensive than a skirt.wav', 'mixer_2.png', 'skirt_2.png'],
    [3, 113, 3, 'participant', 'hoover_2.png', 'bench_2.png'],
    [3, 114, 3, 'A pencil is cheaper than a radio.wav', 'pencil_2.png', 'radio_2.png'],
    [3, 115, 3, 'participant', 'Aeroplane_2.png', 'spoon_2.png'],
    [3, 116, 3, 'A lock is more expensive than a rubber.wav', 'Lock_2.png', 'rubber_2.png'],
    [3, 117, 3, 'participant', 'razor_2.png', 'glasses_2.png'],
    [3, 118, 3, 'A sledge is more expensive than a whistle.wav', 'Sledge_2.png', 'whistle_2.png'],
    [3, 119, 3, 'participant', 'camera_2.png', 'basket_2.png'],
    [3, 120, 3, 'A cake is cheaper than a camera.wav', 'cake_2.png', 'camera_2.png'],
    [3, 121, 3, 'participant', 'drum_2.png', 'lipstick_2.png'],
    [3, 122, 3, 'A rubber is cheaper than a tent.wav', 'rubber_2.png', 'tent_2.png'],
    [3, 123, 3, 'participant', 'egg_2.png', 'button_2.png'],
    [3, 124, 3, 'A tie is cheaper than a sledge.wav', 'tie_2.png', 'Sledge_2.png'],
    [3, 125, 3, 'participant', 'bed_2.png', 'skirt_2.png'],
    [3, 126, 3, 'A shoe is more expensive than a balloon.wav', 'shoe_2.png', 'balloon_2.png'],
    [3, 127, 3, 'participant', 'trumpet_2.png', 'rubber_2.png'],
    [3, 128, 3, 'A candle is more expensive than a sandwich.wav', 'candle_2.png', 'sandwich_2.png'],
    [3, 129, 3, 'participant', 'Sledge_2.png', 'hammer_2.png'],
    [3, 130, 3, 'A knife is cheaper than a lorry.wav', 'knife_2.png', 'lorry_2.png'],
    [3, 131, 3, 'participant', 'violin_2.png', 'tie_2.png'],
    [3, 132, 3, 'A wallet is more expensive than a dustbin.wav', 'wallet_2.png', 'dustbin_2.png'],
    [3, 133, 3, 'participant', 'apple_2.png', 'umbrella_2.png'],
    [3, 134, 3, 'A chair is cheaper than a violin.wav', 'chair_2.png', 'violin_2.png'],
    [3, 135, 3, 'participant', 'wallet_2.png', 'barbecue_2.png'],
    [3, 136, 3, 'A lorry is more expensive than a blanket.wav', 'lorry_2.png', 'blanket_2.png'],
    [3, 137, 3, 'participant', 'clock_2.png', 'apple_2.png'],
    [3, 138, 3, 'A dustbin is cheaper than a radio.wav', 'dustbin_2.png', 'radio_2.png'],
    [3, 139, 3, 'participant', 'volleyball_2.png', 'toothbrush_2.png'],
    [3, 140, 3, 'A watermelon is cheaper than a shoe.wav', 'watermelon_2.png', 'shoe_2.png'],
    [3, 141, 3, 'participant', 'pencil_2.png', 'lorry_2.png'],
    [3, 142, 3, 'An umbrella is cheaper than a car.wav', 'umbrella_2.png', 'Car_2.png'],
    [3, 143, 3, 'participant', 'belt_2.png', 'dustbin_2.png']
  ]
];
